apiVersion: batch/v1
kind: Job
metadata:
  name: experiment-producer-job
spec:
  completions: 4
  parallelism: 2
  backoffLimit: 4
  template:
    spec:
      containers:
        - name: experiment-producer
          image: dclandau/cec-experiment-producer:latest
          args: [
              "--topic", "{{TOPIC}}", 
              "--brokers", "13.60.146.188:19093,13.60.146.188:29093,13.60.146.188:39093",
            ]
          volumeMounts:
            - name: config-vol
              mountPath: /app/experiment-producer/auth
      volumes:
        - name: config-vol
          configMap:
            name: kafka-auth
            items:
              - key: kafka.truststore.pkcs12
                path: kafka.truststore.pkcs12
              - key: kafka.keystore.pkcs12
                path: kafka.keystore.pkcs12
              - key: ca.crt
                path: ca.crt
      restartPolicy: Never
